### ISSUE TITLE
Фильтрация новых бонусов

### ISSUE THREAD

**Issue by hevav** [xTCry/VCoin#27]
В VK Coin добавили еще два бонуса: vkp1 и vkp2, поэтому  на строке 509 VCoinWS нужно добавить их фильтрацию: `this.stack = Entit.generateStack( items.filter(e=> ("bonus" !== e && "vkp1"!== e&&"vkp2"!== e)) );`

**Comment by hevav** [comment]
Если эти бонусы не фильтровать, то будет ошибка 
` /VCoin/VCoinWS.js:515
                        total += Entit.items[n].amount * a;
                                                ^
TypeError: Cannot read property 'amount' of undefined
    at /home/ilinpl/VCoin/VCoin/VCoinWS.js:515:28
    at Array.forEach (<anonymous>)
    at Miner.updateStack (/home/ilinpl/VCoin/VCoin/VCoinWS.js:511:14)
    at VCoinWS.vConinWS.onUserLoaded [as onUserLoadedCallback] (/home/ilinpl/os/VCoin/VCoin/index.js:97:8)
    at WebSocket.ws.onmessage (/home/ilinpl/VCoin/VCoin/VCoinWS.js:108:41)
    at WebSocket.onMessage (/home/ilinpl/VCoin/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (/home/ilinpl/VCoin/node_modules/ws/lib/websocket.js:789:20)
    at emitOne (events.js:116:13)`

**Comment by fakemancat** [comment]
А я попытался фиксануть это циклом, чтобы пропускать undefined. Не знал про новые бонусы
![image](https://user-images.githubusercontent.com/33839807/55584876-c66afd00-573e-11e9-999f-91bcb2bcbe35.png)
