### ISSUE TITLE
смартбуй криво работает

### ISSUE THREAD

**Issue by RUr1ck** [xTCry/VCoin#34]
TypeError: Cannot read property 'send' of null
    at Promise (C:\*некий_путь*\VCoinWS.js:341:32)
    at new Promise (<anonymous>)
    at VCoinWS.sendPack (C:\*некий_путь*\VCoinWS.js:335:10)
    at VCoinWS.queueTick (C:\*некий_путь*\VCoinWS.js:355:15)
    at Timeout.setTimeout [as _onTimeout] (C:\*некий_путь*\VCoinWS.js:361:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by MarkelovZ** [comment]
Та же проблема. И вся консоль за секунду уходит в спам этой ошибкой

**Comment by kyoukisu** [comment]
У меня смартбай и автобай ничего не закупают

**Comment by MarkelovZ** [comment]
Тоже перестал сейчас закупать

**Comment by MarkelovZ** [comment]
Резко со всех аккаунтов стало работать и закупать

**Comment by kyoukisu** [comment]
тоже
--
перестал
--
заработало. чет я косячу
