### ISSUE TITLE
Error: Cannot find module 'beepbeep'

### ISSUE THREAD

**Issue by agalq12** [xTCry/VCoin#62]
Error: Cannot find module 'beepbeep'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\Users\artem\Downloads\VCoin-master\helpers.js:5:9)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)

**Comment by M99BE** [comment]
найс токен спалил кста

**Comment by Cobr3n** [comment]
npm i beepbeep

**Comment by TheKoT** [comment]
> npm i beepbeep

Спасибо

**Comment by TheKoT** [comment]
У всех так?
try start...
boost started
onBrokenEvent

**Comment by Cha14ka** [comment]
да

**Comment by mlv-dev** [comment]
Решение: npm install beepbeep
Но ничего всё равно не работает

**Comment by agalq12** [comment]
КЛАСС,спалил токен теперь с мои vcoin тупа снимают,что делать

**Comment by Cha14ka** [comment]
В настройках аккаунта на сайте нажми выйти со всех устройств. Оно удалит все старые токены и сделает их не рабочими

**Comment by agalq12** [comment]
> 
> 
> В настройках аккаунта на сайте нажми выйти со всех устройств. Оно удалит все старые токены и сделает их не рабочими

Спасибо!!!!
